services:
  forgesampleoffers.webapi:
    image: forgesampleoffers.webapi
    build:
      context: .
      dockerfile: areas/ForgeSampleOffers/ForgeSampleOffers.WebApi/Dockerfile
    container_name: forge-sampleoffers.webapi       
      
  seq:
    image: datalust/seq
    container_name: forge-seq
    restart: always
    ports:
      - "5341:80" # Port SEQ
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
  
volumes:
  seq-data:
